Repository canonical/mysql-router-operator, pull requests merged in 2025-02, with the labels that each got.

#219 [DPE-6653] Signal outdated charm libs with a label
  .github/workflows/check_libs.yaml
  .github/workflows/ci.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#220 feat: dpe-6306 Static code analysis
  .github/actionlint.yaml
  .github/workflows/tiobe_scan.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#179 Always return VIP as host if set
  src/charm.py
  src/relations/hacluster.py
Labels: Libraries: Out of sync

#224 [DPE-6651] Update snap revisions to new builds with updated percona packages
  src/snap.py
Labels: enhancement, Libraries: Out of sync

#225 [DPE-6652] Refresh all charm libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/grafana_agent/v0/cos_agent.py
  lib/charms/operator_libs_linux/v2/snap.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  poetry.lock
  pyproject.toml
Labels: not bug or enhancement, Libraries: Out of sync
